#!/usr/bin/env python3
"""Regenerate content/skillup/catalog.json from each exam's own index.json.

Usage: python3 scripts/generate-catalog.py

Auto-discovers content/skillup/*/index.json, recounts questions from the
actual question JSON files, updates each index.json in place if its stated
count drifted, then writes catalog.json fresh. catalog.json is generated,
never hand-edited — same rule as when this logic lived in ajch_platform's
sync-stats.py (this repo's own copy of that logic, ported here since
catalog.json's raw source content now lives here, not there).

Run this after any change to an exam's index.json or question files, before
promoting a new commit SHA via ajch_platform's promote-content workflow.
"""
import json
import glob
import os
from datetime import date


def count_questions_in_files(question_files: list) -> int:
    """Count actual question objects across a list of question JSON paths."""
    total = 0
    for rel_path in question_files:
        if os.path.exists(rel_path):
            try:
                with open(rel_path, encoding="utf-8") as f:
                    total += len(json.load(f))
            except Exception:
                pass
    return total


def generate_catalog() -> None:
    skill_files = sorted(glob.glob("content/skillup/*/index.json"))
    skills = []
    for path in skill_files:
        with open(path, encoding="utf-8") as f:
            skill = json.load(f)

        # Auto-recount questions from actual question JSON files
        q_files = skill.get("questionFiles", [])
        if q_files:
            actual_count = count_questions_in_files(q_files)
            if actual_count > 0 and skill.get("questions") != actual_count:
                print(f"  [{skill['id']}] questions: {skill.get('questions', '?')} → {actual_count}")
                skill["questions"] = actual_count
                with open(path, "w", encoding="utf-8") as f:
                    json.dump(skill, f, indent=2)

        skills.append(skill)

    if not skills:
        print("No exams found under content/skillup/*/index.json — nothing to do.")
        return

    catalog = {
        "schemaVersion": "1.0",
        "generated": str(date.today()),
        "note": "Auto-generated by scripts/generate-catalog.py from skillup/*/index.json. Do not edit manually.",
        "exams": skills,
    }
    out = "content/skillup/catalog.json"
    with open(out, "w", encoding="utf-8") as f:
        json.dump(catalog, f, indent=2)
        f.write("\n")
    print(f"Catalog written: {len(skills)} skills -> {out}")


if __name__ == "__main__":
    generate_catalog()
